### ISSUE TITLE
Where to buy plutonium?

### ISSUE THREAD

**Issue by spacehuhn** [TheDuchy/OpenSourceNuclearWarhead#2]
Hey guys,

I was just at ALDI and seems like they don't sell nuclear materials. 
Can you help me out find something online? 

I looked at eBay and AliExpress already but I think what they sell is not legitimate material, has someone experience with this?
That's what it looks like:  

![grafik](https://user-images.githubusercontent.com/3826044/46177638-ed3e0780-c2b3-11e8-900a-e22e11b976b6.png)

Thanks everyone, special thanks goes to the NSA, GCHQ, BND and CNI reading this ❤️

**Comment by tobozo** [comment]
Actually MOX is better than plutonium (it's dirty plutonium) and has a much longer half life (see Fuckyoushima).

![image](https://user-images.githubusercontent.com/1893754/46196466-75013180-c307-11e8-8489-3c3e3c8ec6d8.png)

**Comment by That-Thing** [comment]
Pretty sure Kroger's sells that stuff

**Comment by TheDuchy** [comment]
We will stay with the good ol' UrAnusium. Won't fix.

P.S: cheers NSA, FBI etc.
